# Simple NN in python with 1 hidden layer

This NN model is a naive implementation of a Neural Network in Python and is going to be used to train and then compare and test with a few embedded platforms. The class code is taken from [here](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py).

## Prerequisites
You need to install jupyter notebook for this example to run. The easiest way is to install miniconda and then use conda to install nupmy and jupyter.

In [1]:
import numpy as np

In [2]:
class NeuralNetwork():
    def __init__(self, training_set_inputs, training_set_outputs):
        
        self.input = training_set_inputs
        self.y = training_set_outputs
        
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        np.random.seed(1)
        # Create a 3-4-1 network
        self.weights1   = np.random.rand(self.input.shape[1],32) 
        self.weights2   = np.random.rand(32,1)

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through the hidden layer
            output = self.__sigmoid(np.dot(training_set_inputs, self.weights1))
            # 2nd layer
            output2 = self.__sigmoid(np.dot(output, self.weights2))

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output2

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.            
            d_weights2 = np.dot(output.T, (2*(self.y - output2) * self.__sigmoid_derivative(output2)))
            d_weights1 = np.dot(training_set_inputs.T,  (np.dot(2*(self.y - output2) * self.__sigmoid_derivative(output2), self.weights2.T) * self.__sigmoid_derivative(output)))

            # Adjust the weights.
            self.weights1 += d_weights1
            self.weights2 += d_weights2

    # The neural network predicts.
    def predict(self, inputs):
        output = self.__sigmoid(np.dot(inputs, self.weights1))
        # 2nd layer
        return self.__sigmoid(np.dot(output, self.weights2))


## 1. Create a labeled train set with data and labels.

Now we need to create our input data and then label them. In this case `label` just means the output, so we have two labels 0 and 1, or you can just think of these labels as binary outputs, in this case. The data are those on the next table:

D2 | D1 | D0 | Label
-|-|-|-
0 | 0 | 1 | 0
1 | 1 | 1 | 1
1 | 0 | 1 | 1
0 | 1 | 1 | 0

In Python the above table is translated to those two arrays:

In [4]:
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0, 1, 1, 0]]).T

## 2. Intialise a single neuron neural network

First we need to create an `NeuralNetwork` object and initialize it. In this case initialization means that the weights will get a random value, but with using a constant seed, so the weights are re-producable per run.

In [5]:
neural_network = NeuralNetwork(training_set_inputs, training_set_outputs)

In [6]:
print("Random starting synaptic weights:")
print(neural_network.weights1)

Random starting synaptic weights:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
  3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
  2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01
  4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01
  8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
  8.76389152e-01 8.94606664e-01 8.50442114e-02 3.90547832e-02
  1.69830420e-01 8.78142503e-01 9.83468338e-02 4.21107625e-01]
 [9.57889530e-01 5.33165285e-01 6.91877114e-01 3.15515631e-01
  6.86500928e-01 8.34625672e-01 1.82882773e-02 7.50144315e-01
  9.88861089e-01 7.48165654e-01 2.80443992e-01 7.89279328e-01
  1.03226007e-01 4.47893526e-01 9.08595503e-01 2.93614148e-01
  2.87775339e-01 1.30028572e-01 1.93669579e-02 6.78835533e-01
  2.11628116e-01 2.65546659e-01 4.91573159e-01 5.33625451e-02
  5.74117605e-01 1.46728575e-01 5.89305537e-01 6.99758360e-01
  1.02334429e-01 4.14055988e-01 6.9

## 3. Train the neural network. using a training set.

Now using the above training set we can train our NN. To do that we can run it 10,000 times and make small adjustments each time.

In [7]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

print("New weights_1 after training: \n")
print(neural_network.weights1)

New weights_1 after training: 

[[ 1.54590308  1.07397985 -2.25466028  0.33811102 -1.12867717 -0.64943667
   0.42986236 -0.02123101  1.39225761  0.51070309 -0.92220837  2.0741712
  -0.05017488  2.49477885 -1.80706516  0.02225123  0.93510436  1.09748357
  -1.78366068  0.48039307  2.11263888  1.80570217  0.64619332 -0.01244945
   0.33251036  0.42452356 -1.68604411 -1.66573637  0.79887192  1.29312793
  -0.43412689  1.48948002]
 [ 0.69719797  0.36646416  0.30634185  0.18639117  0.39957133  0.63840783
  -0.13419254  0.63404142  0.74280831  0.64542963  0.09757257  0.43168644
  -0.05348975  0.08756483  0.49330491  0.22541316  0.0984272  -0.03142329
  -0.19527752  0.54879648 -0.00276267 -0.07486475  0.35662824 -0.01086095
   0.58248215  0.12340923  0.36808708  0.31160506 -0.02433671  0.22188673
   0.52353881  0.23293827]
 [-0.80204135 -0.06064239  0.75853612  0.14588782  0.7447778   0.36529958
   0.44643259 -0.09007896 -0.68772053  0.46804819  0.3949623  -0.96859334
   0.62717293 -1.02772198  

In [8]:
print("New weights_2 after training: \n")
print(neural_network.weights2)

New weights_2 after training: 

[[ 1.49230844]
 [ 0.72051863]
 [-2.71804102]
 [ 0.03226573]
 [-1.50402732]
 [-0.91290899]
 [ 0.09985538]
 [-0.28420261]
 [ 1.31793525]
 [ 0.04681985]
 [-1.32379375]
 [ 2.0612959 ]
 [-0.42702707]
 [ 2.5197239 ]
 [-2.14410923]
 [-0.59546252]
 [ 0.63146443]
 [ 0.77656747]
 [-2.26835508]
 [ 0.27245133]
 [ 1.98377998]
 [ 1.54681141]
 [ 0.39326437]
 [-0.74995467]
 [-0.48852328]
 [-0.27687177]
 [-2.04979737]
 [-2.0214732 ]
 [ 0.56493531]
 [ 0.90879945]
 [-0.6690652 ]
 [ 1.34212305]]


## 4. Test the trained model

Now that we have a trained NN, we can test it by passing input data that it doesn't know about.


In [9]:
# All possible inputs
inputs = np.array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]])

In [10]:
for i in range(0, 8):
    print("{} = {}".format(inputs[i], neural_network.predict(inputs[i])))

[0 0 0] = [0.29705808]
[0 0 1] = [0.00288461]
[0 1 0] = [0.24794368]
[0 1 1] = [0.00253667]
[1 0 0] = [0.99992702]
[1 0 1] = [0.99790474]
[1 1 0] = [0.99989151]
[1 1 1] = [0.99714449]
